---
title: "R、Pythonを用いた統計分析等について"
date: "2024-09-"
execute: 
  error: true
  cache: true
format:
  html: 
    slide-level: 2
    toc: true
---

# 概要

ここでは、R、Pythonを用いた統計分析や経済学の知識、コード管理の手法としてのGitHubの基本的な使い方を整理します。

# 目次

1. [GitHub](#1-github)
2. [R](#2-r)
3. [Python](#3-python)
4. [計量経済学](#4-計量経済学)
5. [データサイエンス](#5-データサイエンス)
6. [その他](#6-その他)

## 1. GitHub {#1-github}
GitHubの基本的な使い方を整理します。  

- [GitHubについて](git_memo.html)

## 2. R {#2-r}
Rの基本的な使い方を整理します。

### R×データサイエンス
- [0.Rについて](0.R.html)
- [1.データの可視化](1.データの可視化.html)
- [2.基本](2.基本.html)
- [3.データ変換](3.データ変換.html)
- [4.コードスタイル](4.コードスタイル.html)
- [5.データの整理](5.データの整理.html)

⇒Rではじめるデータサイエンス  [Amazonで見る](https://www.amazon.co.jp/R%E3%81%A7%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%E3%82%B5%E3%82%A4%E3%82%A8%E3%83%B3%E3%82%B9-Hadley-Wickham/dp/487311814X)


### R×実証分析
- [1.回帰分析の目的](1.回帰分析の目的.html)
- [2.統計の基礎知識](2.統計の基礎知識.html)

⇒Rによる実証分析 (第2版): 回帰分析から因果分析へ[Amazonで見る](https://www.amazon.co.jp/R%E3%81%AB%E3%82%88%E3%82%8B%E5%AE%9F%E8%A8%BC%E5%88%86%E6%9E%90-%E7%AC%AC2%E7%89%88-%E5%9B%9E%E5%B8%B0%E5%88%86%E6%9E%90%E3%81%8B%E3%82%89%E5%9B%A0%E6%9E%9C%E5%88%86%E6%9E%90%E3%81%B8-%E6%98%9F%E9%87%8E-%E5%8C%A1%E9%83%8E/dp/4274230023)

## 3. Python {#3-python}
Pythonの基本的な使い方を整理します。  

- [Pythonについて](section1.html)

## 4. 計量経済学 {#4-計量経済学}
計量経済学の基本的な知識を整理します。  

- [計量経済学について](section1.html)

## 5. データサイエンス {#5-データサイエンス}
データサイエンスの基本的な知識を整理します。  

- [データサイエンスについて](section1.html)

## 6. その他 {#6-その他}
その他、関連知識を整理します。  

- [VS Codeショートカット一覧](shortcut.html) 
- [応用一般均衡モデルについて](section1.html)
